### ISSUE TITLE
Dodanie do panelu ustawień użytkownika preferowanej waluty (jednej z trzech - znaleźć jakiś lib co to tłumaczy USD na PLN etc)

### ISSUE THREAD

**Issue by x0-lf** [JapaneseZgredek/Cont-Air-Near#102]

**Comment by JapaneseZgredek** [comment]
Można zrobić, za dużo roboty przy tym raczej nie będzie, można dodać do tabeli co trzyma cene po prostu dodatkowe ceny przeliczane odrazu przy tworzeniu obiektu typu price_usd, price_euro etc. A potem tylko zależnie co wybierzemy na frontendzie, to podmieniamy cene z rekordów które i tak trzymamy w jakiejś liście na frontendzie no bo je pobraliśmy na samym początku jak wchodziłęś w strone Product
